version: '3.4'

services:
  daochain_dbservice: 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8889:80"

  daochain_db: 
    ports:
      - 3309:3306
 
  daochain_logsdb: 
    ports:
      - 3310:3306

  daochain_votedb: 
    ports:
      - 3312:3306
 
  daochain_reputationdb: 
    ports:
      - 3313:3306
      
  daochain_identityservice: 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8890:80"

  daochain_logservice: 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8891:80"

  daochain_notificationservice: 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8892:80"

  daochain_apigateway: 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8896:80"

  daochain_votingengine: 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8897:80"

  daochain_reputationservice: 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8898:80"

  daochain_webportal: 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8895:80"
